### ISSUE TITLE
where is the firefox addon?

### ISSUE THREAD

**Issue by faystart** [oskarjakiela/trello-web-clipper#1]
would you please tell me ?

**Comment by oskarjakiela** [comment]
It seems the extension has been delete from Mozilla Addons. I'm going to re-upload it again, so it will be available today (I hope).

**Comment by oskarjakiela** [comment]
I re-submitted a new version 0.2.7. It is available at https://addons.mozilla.org/pl/firefox/addon/trello-web-clipper/
