### ISSUE TITLE
Cannot re-authorize after Chrome profile wipe

### ISSUE THREAD

**Issue by xtoq** [oskarjakiela/trello-web-clipper#2]
## Steps to reproduce
1. Ensure you're using Chrome with account sync enabled.
2. Install Trello Web Clipper.
3. Authorize the app by clicking on the icon.
4. Wipe the current Chrome profile by uninstalling and reinstalling Chrome, or physically deleting the profile folder. (I can reproduce both ways, and both are suggested by Google/Chrome help.)
5. Create a new Chrome profile, using the same account as previously, and wait for the sync to finish.
6. Click the Trello Web Clipper icon.
## Expected outcome
- You should either be asked to authorize again, or the authorization should still be available. (Not sure which is more feasible with Chrome extensions and a profile reset.)
## Actual outcome
- The tooltip says, "Something goes wrong" and nothing happens. No popups or new tabs open,  nor any processes or other visible interface opens or appears.
## Additional information
- Chrome v 47.0.2526.106 m
- Windows 10 Pro 64-bit (Threshold 2 update)
- The only way to fix it is to uninstall the extension then reinstall it from the web store. After this, it will again ask for re-authorization.
- I believe this also happens after the authorization expires (for example, after 30 days) but I've had to reset my profile more than I've been able to let the authorization expire, so it's just a "I think I remember this happened before" scenario.

Please let me know if I need to provide additional information!

**Comment by oskarjakiela** [comment]
I sincerely apologize for the bug (it is really silly one, and I feel ashamed...) and the hotfix is on the way. I'm going to release a new version today.

Thank you for using my extension!

**Comment by xtoq** [comment]
No worries! I just confirmed it does happen when the authorization expires as well; I set it to expire in 1 hour 2 hours ago, and I get the same error now when trying to save cards.

Thanks for making it, and I'm glad the fix was easy. Don't feel ashamed for bugs, even "silly" ones because they help us learn & be better programmers. I've "learned" a lot over the years...if ya know what I mean. ;)

**Comment by oskarjakiela** [comment]
Thank you for positive encouragement :) New version 0.2.7 is now available at Chrome Web Store.

**Comment by xtoq** [comment]
Thanks! Working perfectly. =)
